# Generated by Django 2.1.5 on 2019-07-11 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20190711_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 17, 31, 45, 301017), verbose_name='date published'),
        ),
    ]
