# Generated by Django 2.1.5 on 2019-07-12 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190711_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 6, 7, 12, 550847), verbose_name='published on'),
        ),
    ]
