# Generated by Django 2.1.5 on 2019-07-12 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190712_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 12, 6, 14, 19, 76117), verbose_name='published on'),
        ),
    ]
