# Generated by Django 2.1.5 on 2019-02-04 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190131_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 4, 13, 17, 56, 627746), verbose_name='date published'),
        ),
    ]
