# Generated by Django 2.1.5 on 2019-03-17 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190204_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 17, 18, 30, 2, 522798), verbose_name='date published'),
        ),
    ]
