# Generated by Django 2.1.5 on 2019-07-11 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190711_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 9, 36, 49, 6195), verbose_name='date published'),
        ),
    ]
