# Generated by Django 2.1.5 on 2019-07-13 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20190713_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 18, 27, 48, 452884), verbose_name='date published'),
        ),
    ]
