# Generated by Django 2.1.5 on 2019-07-13 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20190713_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 19, 12, 26, 656280), verbose_name='date published'),
        ),
    ]
