# Generated by Django 2.1.5 on 2019-07-14 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20190713_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 6, 35, 17, 120479), verbose_name='date published'),
        ),
    ]
