# Generated by Django 2.1.5 on 2019-07-14 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20190714_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 18, 24, 3, 155391), verbose_name='date published'),
        ),
    ]
