# Generated by Django 2.1.5 on 2019-07-14 18:02

import datetime
from django.db import migrations, models
import filebrowser.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20190714_0635'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=filebrowser.fields.FileBrowseField(blank=True, max_length=200, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 18, 2, 19, 155757), verbose_name='published on'),
        ),
    ]
