# Generated by Django 2.1.5 on 2019-07-14 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20190714_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 18, 2, 19, 132948), verbose_name='date published'),
        ),
    ]
