# Generated by Django 2.1.5 on 2019-07-14 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190714_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 14, 18, 16, 21, 211115), verbose_name='date published'),
        ),
    ]
