# Generated by Django 2.1.5 on 2019-07-13 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20190711_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 15, 28, 28, 478336), verbose_name='date published'),
        ),
    ]
