# Generated by Django 2.1.5 on 2019-07-11 11:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190711_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 11, 20, 14, 44765), verbose_name='date published'),
        ),
    ]
