# Generated by Django 2.1.5 on 2019-07-11 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190711_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 11, 11, 54, 45, 706823), verbose_name='date published'),
        ),
    ]
